# ---------------------------------------------------------------------
#+STARTUP:          content showstars indent
#+EXCLUDE_TAGS:     journal noexport
#+ARCHIVE:          ~/dox/wrk/pfe/docs/thesis_infra/thesis.archive.org
# ---------------------------------------------------------------------
* Overview
@@latex:\noindent@@
Nowadays, the world is witnessing an increase in the number of ac:iot devices and their various
applications in various fields, resulting in the generation of enormous data.
These data generated by the acrshort:iot devices require a solution for processing, and most
acrshort:iot applications use Cloud computing as the primary solution to process the data generated
by the acrshort:iot devices, according to the performance and high computation resources offered
by the cloud to process High volume of data.   

But the cloud computing by its centralization paradigm lead to some critical problems which is, the
network bandwidth , the latency and security issue these problems  affect the acrshort:iot application
especially the application that need a real-time respond.
Edge and fog computing by the distributed computing paradigms will help reducing the compute and storage
resource overloading at cloud infrastructure by exploiting the resources close to the data source
generated by acrshort:iot devices

** Edge computing & Video surveillance system
@@latex:\noindent@@
acrlong:vss Based on [[ac:cctv]], become one of most important  Real-time acrshort:iot Application, and 
fundamental part of the Security System, Video Surveillance systems developed from the purpose of
indoor monitoring to recently, developed to perform video analytic, like suspicious behavior
activity detection , human face recognition etc .
With the emergence of edge computing to surveillance systems, real time processing can be done,
Using edge computing almost eliminated network and computational latency.
And gain more security and privacy of the data .

** Problem and Contributions
@@latex:\noindent@@
The Application of Edge computing resolves the problems of centralizing the processing on the
cloud computing , and benefit the reduce processing times and improve application performance by
distributing and locating the processing and storage near to data sources.

In order to deploy a critical and real-time application such as acrlong:vss on edge computing,
the edge computing infrastructure has to be Highly available, easy to deploy, scalable and secure.

** Purpose and goals
@@latex:\noindent@@
Recently about the topic of applying edge computing solution as a Modern computing paradigm,
there's a researches that try to gives a technological solutions that address the challenges on
edge computing.

Our Goal of this thesis is to explain our edge computing infrastructure solution that meet the
principal key factors:

- High Availability ({{{crefs(ha)}}})
- Real Time respond
- Scalability ({{{crefs(pr_and_auto)}}}, {{{crefs(storage)}}})
- Security ({{{crefs(virt)}}})
- Easy deployment ({{{crefs(cont_and_micro)}}})   
** Thesis Structure
@@latex:\noindent@@
In this Graduation project report we will discuss in details, the set theory and fundamental
concepts related to our proposed edge computing infrastructure solution in Chapter[[id:chp2][2]] , and in
Chapter[[id:chp3][3]] our detailed solution that cover design , implementation and core technologies used to
acheive our Goal from this project.


* Local Variables                                           :noexport:ignore:
# Local Variables:
# mode: org
# org-export-allow-bind-keywords: t
# eval: (setq display-fill-column-indicator-column 100)
# eval: (display-fill-column-indicator-mode)
# eval: (flyspell-mode t)
# End:
